### ISSUE TITLE
有些细节问题

### ISSUE THREAD

**Issue by 985892345** [Watermelon9999/PetsCoffee#1]
## 比如：
```kotlin
class DirectionView(context: Context?, attrs: AttributeSet?)
```
中的 context 是一定不为空的，可以把问号去掉
```kotlin
override fun onTouchEvent(event: MotionEvent?): Boolean  // 这个 MotionEvent 也一样
override fun onDraw(canvas: Canvas?) // 这个 Canvas 也一样
```
其实这个是 kt 识别 java 的问题，因为他也不知道会不会为空，但开发者知道的话，可以去掉问号，这样书写起来要好一些，用起来也不用再去判断

## 分包
ui 层可以再分细一点，比如：
- ui
- - main 主界面
- - - activity
- - - fragment
- - shop 商店界面
- - - activity
- - - fragment

## onDraw() 里面不要进行复杂的操作
```kotlin
// 在你写的 WindowView.kt 中
override fun onDraw(canvas: Canvas?) {
    super.onDraw(canvas)
    Glide.with(this).load(R.drawable.mainpage_background_1).into(this)
}
```
你竟然在 onDraw() 里面写 Glide 。。。
onDraw、onLayout、onMeasure 这些方法里面都不建议进行耗时操作，因为他们是每隔十几毫秒就回调一次，如果有耗时操作很容易造成卡顿，比如 io 流、new 对象
```kotlin
// WorkView.kt 的 onDraw() 中也是直接 new 对象，这样操作会在短时间内生成大量对象
override fun onDraw(canvas: Canvas?) {
    super.onDraw(canvas)
    pathMeasure = PathMeasure(path, false)
}
```

总的来说写得很不错了，自己还写了后端，也确实太卷了😂

**Comment by Watermelon02** [comment]
谢谢郭神，？这个我确实不知道，不过关于？，我想知道一般来说网络请求是不是最好都加个？避免丢包的情况。
glide这个之后会改，没想到学长竟然看的这么细

**Comment by 985892345** [comment]
网络请求肯定要判断
但自定义 View 这边那个 context、MotionEvent、Canvas 是肯定不为空的，kt 在重写时自动打上问号是因为它无法识别 java 的原方法是否为空，所以为了安全，就直接打上问号了
那个东西如果自己知道肯定不为空的话，建议自己去掉形参中的问号，这样少写一些判断

**Comment by Watermelon02** [comment]
好的，以后再写会注意
